# Generated by Django 3.2.1 on 2022-03-31 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_course_classtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='classTime',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
