# Generated by Django 3.2.1 on 2022-03-31 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_course_classtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
